# Generated by Django 4.2.4 on 2023-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0012_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(max_length=10),
        ),
    ]
