# Generated by Django 4.2.4 on 2023-08-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0013_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
