# Generated by Django 4.2.4 on 2023-08-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0014_delete_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255)),
                ('itemcount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('items', models.TextField()),
                ('ref_num', models.CharField(default='7724194257', editable=False, max_length=10, unique=True)),
            ],
        ),
    ]
