# Generated by Django 4.2.4 on 2023-08-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0015_currenttransaction_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='1383661188', editable=False, max_length=10, unique=True),
        ),
    ]
