# Generated by Django 4.2.4 on 2023-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0016_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='5570218121', editable=False, max_length=10, unique=True),
        ),
    ]
