# Generated by Django 4.2.4 on 2023-08-09 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0020_alter_receipt_date_alter_receipt_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(default='In Queue', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 4, 32, 46, 680019)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(default='customer', max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='9705970197', max_length=10, unique=True),
        ),
    ]
