# Generated by Django 4.2.4 on 2023-08-10 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0026_alter_receipt_date_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttransaction',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 16, 8, 9, 738046)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='8247278301', max_length=10, unique=True),
        ),
    ]
