# Generated by Django 4.2.4 on 2023-08-10 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0027_currenttransaction_category_alter_receipt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 17, 19, 35, 223757)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='4060624490', max_length=10, unique=True),
        ),
    ]
