# Generated by Django 4.2.4 on 2023-08-11 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0030_alter_receipt_date_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 13, 0, 32, 568297)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='7458576567', max_length=10, unique=True),
        ),
    ]
