# Generated by Django 4.2.4 on 2023-08-13 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0033_alter_receipt_date_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 1, 30, 35, 992143)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='4388891916', max_length=10, unique=True),
        ),
    ]
